### ISSUE TITLE
How to use this from a pure JS ...

### ISSUE THREAD

**Issue by venkatpolisetti** [procurios/ResizeSensor#2]
I am trying to use this in a Salesforce Visualforce page and wondering how to use it without the require. Any help on this?

**Comment by pesla** [comment]
Just include the file:

```js
<script src='/path/to/resizeSensor.min.js'></script>
```

It'll register itself globally:

```js
// { create: ƒ, destroy: ƒ }
console.log(window.resizeSensor); 
```
