### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by benfoxall** [procurios/ResizeSensor#3]
It would be handy to have this published to npm (I just tried to include it through https://unpkg.com/ and realised it's not been published).

**Comment by MartinKolarik** [comment]
You can use https://www.jsdelivr.com/package/gh/procurios/ResizeSensor instead.

**Comment by pesla** [comment]
Thanks for providing a workaround @MartinKolarik. `ResizeSensor` is now published to npm aswell: https://www.npmjs.com/package/procurios.resizesensor.
